name: CD-SFTP

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.SSH_RPI_USER }}
          server: ${{ secrets.SSH_RPI_HOST }}
          port: ${{ secrets.SSH_RPI_PORT }} # default is 22
          ssh_private_key: ${{ secrets.SSH_RPI_PUBLIC_KEY }}

          # will put all file under this path
          local_path: ./dist/* # default is ./*
          # files will copy to under remote_path
          remote_path: /home/${{ secrets.SSH_RPI_USER }}/tpm/

          # sftp args
          args: '-o ConnectTimeout=5'
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_RPI_HOST }}
          username: ${{ secrets.SSH_RPI_USER }}
          key: ${{ secrets.SSH_RPI_PUBLIC_KEY }}
          port: ${{ secrets.SSH_RPI_PORT }}
          script: |
            cd /mnt/serverDrive/www/madebybambi.com 
            sudo rm /home/peta/tpm/config.json
            sudo cp -r /home/peta/tpm/* ./
            sudo chmod -R 755 ./
            sudo chown -R www-data:www-data ./
            sudo systemctl restart nginx
