name: CD-SFTP

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Build
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: peta
          server: madchipmunk03.cz
          port: 2022 # default is 22
          ssh_private_key: ${{ secrets.SSH_RPI_PUBLIC_KEY }}

          # will put all file under this path
          local_path: ./dist/* # default is ./*
          # files will copy to under remote_path
          remote_path: /mnt/serverDrive/www/madebybambi.com/

          # sftp args
          args: '-o ConnectTimeout=5'
